sudo: false
cache: bundler
language: ruby
rvm:
  - 2.4.6
  - 2.5.3
before_install: gem install bundler -v 1.14.4
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a15a36fcd1750318ad5f
    on_success: change
    on_failure: always
    on_start: never
